#FAÇA UM PROGRAMA QUE CALCULE A SOMA ENTRE TODOS OS NÚMEROS ÍMPARES QUE SÃO MÚLTIPLOS DE TRÊS
#E QUE SE ENCONTRAM NO INTERVALO DE '1' ATÉ '500'.
for c in range(1, 500):
    if c % 3 == 0:
        sum()

